/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-bright": "#fcf9f8",
        "inverse-surface": "#313030",
        "alert-crimson": "#7F1C34",
        "surface-variant": "#e5e2e1",
        "healing-teal": "#034F46",
        "secondary": "#6a5778",
        "surface-container-highest": "#e5e2e1",
        "primary-fixed": "#afefe2",
        "on-primary-fixed": "#00201c",
        "on-tertiary-fixed": "#1b1d11",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#6f5b7d",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#d6bee5",
        "secondary-container": "#f0d7ff",
        "surface-container": "#f0eded",
        "on-primary-fixed-variant": "#055047",
        "inverse-on-surface": "#f3f0ef",
        "tertiary": "#2f3124",
        "surface-container-high": "#eae7e7",
        "surface": "#fcf9f8",
        "soft-lavender": "#F0D7FF",
        "tertiary-fixed": "#e3e4d0",
        "surface-dim": "#dcd9d9",
        "surface-container-low": "#f6f3f2",
        "secondary-fixed": "#f2daff",
        "warm-parchment": "#FFFFEB",
        "on-secondary-fixed-variant": "#524060",
        "outline-variant": "#bfc9c5",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#94d2c6",
        "on-primary": "#ffffff",
        "surface-tint": "#29685f",
        "on-primary-container": "#81bfb3",
        "background": "#fcf9f8",
        "primary-container": "#034f46",
        "on-secondary-fixed": "#251432",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#46483a",
        "on-tertiary-container": "#b4b5a3",
        "on-surface": "#1c1b1b",
        "outline": "#6f7976",
        "on-background": "#1c1b1b",
        "tertiary-container": "#454739",
        "primary-fixed-dim": "#94d2c6",
        "primary": "#003630",
        "on-surface-variant": "#3f4946",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#c7c8b5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "8px",
        "margin-desktop": "64px",
        "container-max": "1100px",
        "section-gap": "120px",
        "container-padding": "40px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "transcript-text": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "30px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "transcript-text": ["22px", { lineHeight: "36px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
